### ISSUE TITLE
Links point back to the page being viewed (href=#)

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#23] opened 2016-10-17 20:53 UTC
URL
https://www7.ietf.org/admin/pages/1054/edit/ and
https://www7.ietf.org/how-we-work/meetings/97/

Expected Behaviour
Links in the published page should point to the documents/pages/external links entered into the Link Groups under key details.

Actual Behaviour
All links, regardless of what they're pointed to when edited, point to the page being viewed (href=#), pointing back to the main event page they're on.  No inputted links are published, despite the fact that they are saved to the edited page.

Reproducing
Chrome 54.0.2840.59 / Firefox 49.0.1
OS: Windows 10 Home Edition

**Comment by ghwood** [comment] 2016-10-18 09:56
I think this is a dupe of Issue #15 closing this one and updating #15

**Closed as completed** 2016-10-18 09:56 UTC
